"""reset again

Revision ID: 201f233ff569
Revises: 
Create Date: 2025-03-22 14:04:57.671672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201f233ff569'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports_listing_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'listings_table', ['listing_id'], ['id'])
        batch_op.drop_column('sellers_firstname')
        batch_op.drop_column('listing_name')

    with op.batch_alter_table('reports_reviews_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'reviews_table', ['review_id'], ['id'])
        batch_op.drop_column('reviewed_firstname')
        batch_op.drop_column('reviwer_firstname')

    with op.batch_alter_table('reports_user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reported_user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user_table', ['reported_user_id'], ['id'])
        batch_op.drop_column('reported_user_firstName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports_user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reported_user_firstName', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reported_user_id')

    with op.batch_alter_table('reports_reviews_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviwer_firstname', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('reviewed_firstname', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('review_id')

    with op.batch_alter_table('reports_listing_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sellers_firstname', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('listing_id')

    # ### end Alembic commands ###
