"""Altered FavouritesModel listings_id field name to listing_id to make finding it easier

Revision ID: 8ef8717f12b7
Revises: 201f233ff569
Create Date: 2025-03-23 11:28:03.054498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef8717f12b7'
down_revision = '201f233ff569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favourites_table_listings_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'listings_table', ['listing_id'], ['id'])
        batch_op.drop_column('listings_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listings_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favourites_table_listings_id_fkey', 'listings_table', ['listings_id'], ['id'])
        batch_op.drop_column('listing_id')

    # ### end Alembic commands ###
